### ISSUE TITLE
Two warnings from XCode: (1) 'ValidateLibrary' needs to be declared as 'executableTarget()', and (2) Expression implicitly coerced from 'UnsafeMutableRawPointer?' to 'Any'

### ISSUE THREAD

**Issue by theschles** [philipturner/MoltenCL#2]
<img width="486" alt="image" src="https://user-images.githubusercontent.com/901430/197425919-996ff0f4-6698-40b6-8691-3a3d8304bae5.png">

**Comment by philipturner** [comment]
This driver is still in the prototype stage, so it's not a finished framework yet. I haven't intended for it to be compiled by any users. When I do, there won't be any errors with compiling it in Xcode.

Thanks for your interest in the project's progress, though!
